using Microsoft.AspNetCore.Mvc;

namespace Lab8.Controllers
{
    public class GameController : Controller
    {
        private static int n; // range value
        private static int randValue; // random value
        private static int numberOfTries = 0;
        public IActionResult Index()

        {
            ViewBag.count = numberOfTries;
            return View();
        }

        [HttpGet("/set,{newN}")]
        public IActionResult Set(int newN)
        {
            n = newN;
            numberOfTries = 0;
            ViewBag.count = numberOfTries;
            return RedirectToAction("Index");

        }
        [HttpGet("draw")]
        public IActionResult Draw()
        {
            Random random = new Random();
            int randomNumber = random.Next(1, n + 1);
            randValue = randomNumber;
            numberOfTries = 0;
            ViewBag.count = numberOfTries;
            TempData["RandomValue"] = randValue.ToString();
            return RedirectToAction("Index");
        }
       
        [HttpGet("/guess,{userGuess}")]
        public IActionResult Guess(int userGuess)
        {
            numberOfTries++;
            // Assuming randValue is the target value generated by the "Draw" action
            if (userGuess < randValue)
            {
                TempData["GuessResult"] = "Too Low!";
            }
            else if (userGuess > randValue)
            {
                TempData["GuessResult"] = "Too High!";
            }
            else
            {
                TempData["GuessResult"] = "Correct!";
            }
            ViewBag.count = numberOfTries;


            // Redirect to the "Index" action
            return RedirectToAction("Index");
        }



    }
}
