-- TASK 5 SCRIPT TO DROP TABLES IN SCHEMA

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Shepel_Molenda' AND TABLE_NAME = 'FACT_SALES'

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Shepel_Molenda' AND TABLE_NAME = 'FACT_SALES')
    DROP TABLE Shepel_Molenda.FACT_SALES;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Shepel_Molenda' AND TABLE_NAME = 'DIM_SALESPERSON')
    DROP TABLE Shepel_Molenda.DIM_SALESPERSON;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Shepel_Molenda' AND TABLE_NAME = 'DIM_PRODUCT')
    DROP TABLE Shepel_Molenda.DIM_PRODUCT;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Shepel_Molenda' AND TABLE_NAME = 'DIM_CUSTOMER')
    DROP TABLE Shepel_Molenda.DIM_CUSTOMER;
