-- REMOVE ALREADY EXISTING SCHEMA
IF EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'Crimes_Weather')
BEGIN
	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'FACT_Crimes')
		DROP TABLE Crimes_Weather.FACT_Crimes;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'DIM_Time')
		DROP TABLE Crimes_Weather.DIM_Time;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'DIM_Descent')
		DROP TABLE Crimes_Weather.DIM_Descent;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'DIM_Sex')
		DROP TABLE Crimes_Weather.DIM_Sex;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'DIM_Sunrise_Sunset')
		DROP TABLE Crimes_Weather.DIM_Sunrise_Sunset;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'DIM_Weapon_Used')
		DROP TABLE Crimes_Weather.DIM_Weapon_Used;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'DIM_Premise')
		DROP TABLE Crimes_Weather.DIM_Premise;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'DIM_Crime')
		DROP TABLE Crimes_Weather.DIM_Crime;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'DIM_Area')
		DROP TABLE Crimes_Weather.DIM_Area;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'DIM_Weather_Condition')
		DROP TABLE Crimes_Weather.DIM_Weather_Condition;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'Helper_Month')
		DROP TABLE Crimes_Weather.Helper_Month;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'Helper_Weekday')
		DROP TABLE Crimes_Weather.Helper_Weekday;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'Helper_Season')
		DROP TABLE Crimes_Weather.Helper_Season;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'FACT_Crimes')
		DROP TABLE Crimes_Weather.FACT_Crimes;

	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'TempTable')
		DROP TABLE Crimes_Weather.TempTable;
	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Crimes_Weather' AND TABLE_NAME = 'PreprocessingTable')
		DROP TABLE Crimes_Weather.PreprocessingTable;

	DROP SCHEMA Crimes_Weather;


END
