-- REMOVE ALREADY EXISTING SCHEMA
IF EXISTS (SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'History_Crimes_Weather')
BEGIN
 IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'History_Crimes_Weather' AND TABLE_NAME = 'HIST_DIM_Descent')
  DROP TABLE History_Crimes_Weather.HIST_DIM_Descent;

 IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'History_Crimes_Weather' AND TABLE_NAME = 'HIST_DIM_Sex')
  DROP TABLE History_Crimes_Weather.HIST_DIM_Sex;

 IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'History_Crimes_Weather' AND TABLE_NAME = 'HIST_DIM_Sunrise_Sunset')
  DROP TABLE History_Crimes_Weather.HIST_DIM_Sunrise_Sunset;

 IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'History_Crimes_Weather' AND TABLE_NAME = 'HIST_DIM_Weapon_Used')
  DROP TABLE History_Crimes_Weather.HIST_DIM_Weapon_Used;

 IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'History_Crimes_Weather' AND TABLE_NAME = 'HIST_DIM_Premise')
  DROP TABLE History_Crimes_Weather.HIST_DIM_Premise;

 IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'History_Crimes_Weather' AND TABLE_NAME = 'HIST_DIM_Crime')
  DROP TABLE History_Crimes_Weather.HIST_DIM_Crime;

 IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'History_Crimes_Weather' AND TABLE_NAME = 'HIST_DIM_Area')
  DROP TABLE History_Crimes_Weather.HIST_DIM_Area;

 IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'History_Crimes_Weather' AND TABLE_NAME = 'HIST_DIM_Weather_Condition')
  DROP TABLE History_Crimes_Weather.HIST_DIM_Weather_Condition;

 DROP SCHEMA History_Crimes_Weather;

END
