backend:
  ip: ${BACKEND_IP}
aws:
  cognito:
    logout-uri : ${AWS_COGNITO_LOGOUT_URI}
    domain : ${AWS_COGNITO_DOMAIN}
  s3:
    bucket : ${AWS_S3_BUCKET}

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid
            redirect-uri: https://${CALLBACK_IP}/login/oauth2/code/cognito # TODO : update here redirect uri when do deployment (http -> https)
            clientName: ${CLIENT_NAME}
        provider:
          cognito:
            issuerUri: https://cognito-idp.${AMAZON_REGION}.amazonaws.com/${USER_POOL_ID}
            user-name-attribute: username
server:
  port: 8081

  servlet:
    context-path: /